development:
  host: localhost
  database: karaoke_development

test:
  host: localhost
  database: karaoke_test

# set these environment variables on your prod server
#production:
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
